eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
    refresh:
      enable: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

spring:
  data:
    redis:
      host: localhost
      port: 6379